#!/bin/sh

if [ -z "$1" ]
	then echo '**** usage: ./new [lang] filename'
	exit
fi

if [ "$1" == "c" ]
then 
	touch $2.c
	touch $2.h
	./fwr $2.c ./files.log
	./fwr $2.h ./files.log
	./fwr '//\t'$2.c ./$2.c
	./fwr "//\tcreated `date`" ./$2.c
	./fwr '//\t'$2.h ./$2.h
	./fwr "//\tcreated `date`" ./$2.h
	./rpl 'OBJ=\(.*\)' 'OBJ=\1 '$2.o ./Makefile
	./fwr $2.o: ./Makefile
	./fwr '\t${CC} ${FLAGS} -o '$2'.o -c '$2'.c' ./Makefile
	git add $2.c
	git add $2.h
	echo "**** Created $2.c, $2.h"
else if [ "$1" == "cpp" ]
then
	touch $2.cpp
	touch $2.h
	./fwr $2.cpp ./files.log
	./fwr $2.h ./files.log
	./fwr '//\t'$2.cpp ./$2.cpp
	./fwr "//\tcreated `date`" ./$2.cpp
	./fwr '//\t'$2.h ./$2.h
	./fwr "//\tcreated `date`" ./$2.h
	./rpl 'OBJ=\(.*\)' 'OBJ=\1 '$2.o ./Makefile
	./fwr $2.o: ./Makefile
	./fwr '\t${CC} ${FLAGS} -o '$2'.o -c '$2'.cpp' ./Makefile
	git add $2.cpp
	git add $2.h
	echo "**** Created $2.cpp, $2.h"
else if [ "$1" == "java" ]
then
	touch $2.java
	./fwr $2.java ./files.log
	./fwr "class $2 {" ./$2.java
	./fwr "\n\n}" ./$2.java
	./rpl 'JVC=\(.*\)' 'JVC=\1 '$2.class ./Makefile
	./fwr $2.class: ./Makefile
	./fwr '\tjavac '$2.java ./Makefile
	git add $2.java
	echo "**** Created $2.java"
else if [ "$1" == "py" ]
then
	touch $2.py
	./fwr $2.py ./files.log
	./fwr "#!/usr/bin/python" ./$2.py
	git add $2.py
	echo "**** Created $2.py"
else if [ "$1" == "pl" ]
then
	touch $2.pl
	./fwr $2.pl ./files.log
	./fwr "#!/usr/bin/perl" ./$2.pl
	git add $2.pl
	echo "**** Created $2.pl"
else if [ "$1" == "rb" ]
then
	touch $2.rb
	./fwr $2.rb ./files.log
	./fwr "#!/usr/bin/ruby" ./$2.rb
	git add $2.rb
	echo "**** Created $2.rb"
else if [ "$1" == "sh" ]
then
	touch $2.sh
	./fwr $2.sh ./files.log
	./fwr "#!/bin/sh" ./$2.sh
	git add $2.sh
	echo "**** Created $2.pl"
else
	touch $1.txt
	./fwr $1.txt ./files.log
	./fwr $1.txt ./$1.txt
	git add $1.txt
	echo "**** Created $1.txt"
fi
fi
fi
fi
fi
fi
fi
