#!/bin/sh

if [ -z "$1" ]
	then echo '**** usage: ./project projectname'
	exit
fi

# check if project has already been created
if [ -f ./files.log ]
then
	echo 'project already created'
	exit
else
	# Creates project and initiate git
	echo "**** Creating project $1..."
	git init
fi

# files.log
touch files.log
./fwr files.log ./files.log
git add files.log

#  Makefile
touch Makefile
./fwr Makefile ./files.log

./fwr "# Makefile for $1" ./Makefile
./fwr "CC=clang" ./Makefile
./fwr "FLAGS=-g -Wall -Werror" ./Makefile
./fwr "OBJ=main.o" ./Makefile
./fwr "JVC=" ./Makefile

./fwr "main.o:" ./Makefile
./fwr '\t${CC} ${FLAGS} -o main.o -c main.c' ./Makefile
./fwr 'main: ${OBJ}' ./Makefile
./fwr '\t${CC} ${FLAGS} -o main ${OBJ}' ./Makefile

./fwr 'clean:' ./Makefile
./fwr '\trm ${OBJ} ${JVC} main' ./Makefile

./fwr 'remake: clean main' ./Makefile

git add Makefile

# main.c
touch main.c
./fwr main.c ./files.log

./fwr '//	main.c' ./main.c
./fwr "//	created `date`" ./main.c
./fwr "\n" ./main.c
./fwr "int main(int argc, char *argv[])" ./main.c
./fwr "{" ./main.c
./fwr "\n" ./main.c
./fwr "\n" ./main.c
./fwr "\treturn 0;" ./main.c
./fwr "}" ./main.c

git add main.c

# make first commit for git
git commit -m 'first commit'

echo "**** ....done."

