#!/bin/sh

# print out the summary of project

echo "\t\t\t Project "`sed -n 's/PROJECTNAME=\(.*\)/\1/p' ./vars.log`

started=`sed -n 's/STARTTIME=\(.*\)/\1/p' ./vars.log`
ended=`sed -n 's/ENDTIME=\(.*\)/\1/p' ./vars.log`

echo "Started: "`date -r $started`

if [ $ended -n == 0 ]
then
    echo "Ended: "`date -r $ended`
fi